import { auth, currentUser } from '@clerk/nextjs/server'
import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'

import { JURISDICTION_METADATA } from '@/lib/jurisdiction-metadata'
import { buildAttorneyBriefPdf, type AttorneyBriefPage } from '@/lib/pdf'
import { JURISDICTIONS } from '@/lib/jurisdiction-data'

const requestSchema = z.object({
  generatedAt: z.string(),
  brief: z.object({
    strategy: z.string(),
    fundSize: z.string(),
    lpCount: z.number(),
    lpMix: z.array(z.string()),
    gpDomicile: z.string(),
  }),
  recommendations: z
    .array(
      z.object({
        jurisdiction: z.string(),
        vehicleType: z.string(),
        rank: z.number(),
        reasoning: z.string(),
        estimatedFormationCost: z.object({ min: z.number(), max: z.number() }),
        estimatedTimelineWeeks: z.object({ min: z.number(), max: z.number() }),
      }),
    )
    .min(1),
})

function titleCase(value: string) {
  return value
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join(' ')
}

function getUserAccessLevel(user: Awaited<ReturnType<typeof currentUser>>): 'preview' | 'full' {
  if (!user) return 'preview'

  const metadata = user.publicMetadata ?? {}
  const tier = typeof metadata.tier === 'string' ? metadata.tier.toLowerCase() : ''

  if (tier === 'paid' || tier === 'beta' || metadata.isPaid === true || metadata.betaAccess === true) {
    return 'full'
  }

  return 'preview'
}

export async function POST(request: NextRequest) {
  const { userId } = await auth()
  if (!userId) {
    return NextResponse.json({ success: false, message: 'Authentication required.' }, { status: 401 })
  }

  const payload = await request.json().catch(() => null)
  const parsed = requestSchema.safeParse(payload)

  if (!parsed.success) {
    return NextResponse.json({ success: false, message: 'Invalid request payload.' }, { status: 400 })
  }

  const user = await currentUser()
  const accessLevel = getUserAccessLevel(user)

  const [top, second, third] = parsed.data.recommendations
  const topJurisdiction = JURISDICTIONS.find((entry) => entry.name === top.jurisdiction)
  const meta = topJurisdiction ? JURISDICTION_METADATA[topJurisdiction.id] : undefined

  const today = new Date(parsed.data.generatedAt)
  const renderedDate = Number.isNaN(today.getTime()) ? new Date().toISOString().slice(0, 10) : today.toISOString().slice(0, 10)

  const pages: AttorneyBriefPage[] = [
    {
      title: 'Page 1 — Executive Summary',
      subtitle: `${topJurisdiction?.flag ?? ''} ${top.jurisdiction}`.trim(),
      bullets: [
        `Recommended jurisdiction: ${top.jurisdiction}`,
        `Rationale: ${top.reasoning}`,
        `Recommended vehicle: ${top.vehicleType}`,
        `Fund strategy: ${titleCase(parsed.data.brief.strategy)}`,
        `Fund size: ${titleCase(parsed.data.brief.fundSize)}`,
        `LP count (input): ${parsed.data.brief.lpCount}`,
        `Generated by GNCO on ${renderedDate}`,
        'Disclaimer: For informational purposes only. Not legal advice.',
      ],
    },
    {
      title: 'Page 2 — Structure Overview',
      bullets: [
        `Vehicle description: ${top.vehicleType} is commonly used for cross-border fundraising with flexible LP/GP economics and governance customization.`,
        `Vehicle description: It is typically paired with local counsel, administrator, and audit providers to satisfy launch, compliance, and investor reporting standards.`,
        `Why this fit: Matches current LP/GP profile with priorities around ${parsed.data.brief.lpMix.join(', ') || 'diversified LP mix'}.`,
        `Alternative considered #2: ${second?.jurisdiction ?? 'N/A'} (${second?.vehicleType ?? 'N/A'})`,
        `Alternative considered #3: ${third?.jurisdiction ?? 'N/A'} (${third?.vehicleType ?? 'N/A'})`,
      ],
    },
    {
      title: 'Page 3 — Regulatory Snapshot',
      bullets: [
        `Regulator: ${meta?.regulator.name ?? topJurisdiction?.regulator ?? 'Consult local authority'}`,
        `Contact: ${meta?.regulator.url ?? 'Official regulator website'}`,
        `Registration requirements: Constitutive documents, AML/KYC framework, service provider appointments, and required filings.`,
        `Timeline from formation to launch: ${meta?.timelines ?? `${top.estimatedTimelineWeeks.min}-${top.estimatedTimelineWeeks.max} weeks estimated`}`,
        `Key compliance obligations: ${meta?.key_compliance ?? 'Annual filings, AML/CTF, FATCA/CRS, and ongoing governance obligations.'}`,
      ],
    },
    {
      title: 'Page 4 — Tax Summary',
      bullets: [
        `Headline treatment: ${meta?.tax_headline ?? 'Review local direct and withholding tax profile.'}`,
        `LP domicile considerations: ${parsed.data.brief.lpMix.length ? parsed.data.brief.lpMix.join(', ') : 'Mixed LP profile should be reviewed by counsel by domicile.'}`,
        'WHT implications by LP type: Taxable investors, tax-exempt LPs, and sovereign/foundation capital should each be analyzed for treaty eligibility and reclaim mechanics.',
        `Key treaty set: ${topJurisdiction?.taxTreaties.join(', ') ?? 'Treaty analysis depends on LP domicile and asset jurisdiction.'}`,
      ],
    },
    {
      title: 'Page 5 — Service Provider Requirements',
      bullets: [
        `Required providers: ${meta?.service_providers ?? 'Administrator, auditor, legal counsel, bank/custodian, tax advisor, and compliance support.'}`,
        `Estimated formation cost range: USD ${top.estimatedFormationCost.min.toLocaleString()}-${top.estimatedFormationCost.max.toLocaleString()}`,
        `Estimated annual cost range: USD ${topJurisdiction ? `${topJurisdiction.annualCostRange.min.toLocaleString()}-${topJurisdiction.annualCostRange.max.toLocaleString()}` : 'to be scoped during counsel engagement'}`,
      ],
    },
    {
      title: 'Page 6 — Counsel Briefing Checklist',
      bullets: [
        '1) Is this vehicle optimal for the LP profile and strategy mandate?',
        '2) Which structuring steps reduce withholding tax drag most effectively?',
        '3) Do we require feeder, blocker, or parallel vehicle architecture?',
        '4) What is the critical path to first close and launch?',
        '5) Which registrations and filings are mandatory pre-launch?',
        '6) How should governance rights be allocated between GP and LPs?',
        '7) What side-letter terms are likely for anchor or sovereign LPs?',
        '8) What substance requirements apply to manager and fund entities?',
        '9) Which ongoing compliance calendar items carry highest risk?',
        '10) What assumptions in this brief should be stress-tested first?',
        'Notes: ________________________________________________',
        'Notes: ________________________________________________',
        'Notes: ________________________________________________',
      ],
    },
  ]

  const selectedPages = accessLevel === 'full' ? pages : pages.slice(0, 1)
  const pdf = buildAttorneyBriefPdf(selectedPages)
  const filename = `gnco-attorney-brief-${renderedDate}.pdf`

  return new NextResponse(pdf, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'x-brief-access-level': accessLevel,
      'x-brief-filename': filename,
    },
  })
}
