import * as XLSX from 'xlsx'

import type { ArchitectBrief, FundStructureRecommendation } from '@/lib/types'

export function exportArchitectResults(recommendations: FundStructureRecommendation[], briefData: ArchitectBrief) {
  const wb = XLSX.utils.book_new()

  const summaryData = [
    ['GNCO — FUND STRUCTURE ANALYSIS'],
    ['Generated:', new Date().toLocaleDateString()],
    [''],
    ['INPUT PARAMETERS'],
    ['Fund Strategy:', briefData.strategy?.replace('-', ' ').toUpperCase()],
    ['Target Fund Size:', briefData.fundSize],
    ['GP Domicile:', briefData.gpDomicile],
    ['LP Profile:', briefData.lpProfile?.join(', ')],
    ['Asset Geography:', briefData.assetGeography?.join(', ')],
    ['Top Priority:', briefData.priorities?.[0]?.replace('-', ' ')],
    [''],
    ['TOP RECOMMENDATION'],
    ['Jurisdiction:', recommendations[0]?.jurisdiction],
    ['Vehicle Type:', recommendations[0]?.vehicleType],
    ['Overall Score:', `${recommendations[0]?.scores.overallScore ?? 0}/100`],
    [
      'Formation Cost:',
      `€${recommendations[0]?.estimatedFormationCost.min.toLocaleString()} - €${recommendations[0]?.estimatedFormationCost.max.toLocaleString()}`,
    ],
    ['Timeline:', `${recommendations[0]?.estimatedTimelineWeeks.min}-${recommendations[0]?.estimatedTimelineWeeks.max} weeks`],
  ]
  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData)
  XLSX.utils.book_append_sheet(wb, summarySheet, 'Executive Summary')

  const comparisonData = [
    ['Rank', 'Jurisdiction', 'Vehicle Type', 'Overall Score', 'Tax Efficiency', 'LP Familiarity', 'Formation Cost (Min)', 'Formation Cost (Max)', 'Timeline (Weeks)', 'Best For'],
  ]

  recommendations.forEach((rec, index) => {
    comparisonData.push([
      index + 1,
      rec.jurisdiction,
      rec.vehicleType,
      rec.scores.overallScore,
      rec.scores.taxEfficiency,
      rec.scores.lpFamiliarity,
      rec.estimatedFormationCost.min,
      rec.estimatedFormationCost.max,
      `${rec.estimatedTimelineWeeks.min}-${rec.estimatedTimelineWeeks.max}`,
      rec.bestFor?.[0] || '',
    ])
  })

  const comparisonSheet = XLSX.utils.aoa_to_sheet(comparisonData)
  XLSX.utils.book_append_sheet(wb, comparisonSheet, 'Jurisdiction Comparison')

  const scoringData = [
    ['Jurisdiction', 'Tax Efficiency', 'LP Familiarity', 'Regulatory Simplicity', 'Speed to Close', 'Cost Score', 'Privacy Score', 'Overall Score'],
  ]

  recommendations.forEach((rec) => {
    scoringData.push([
      rec.jurisdiction,
      rec.scores.taxEfficiency,
      rec.scores.lpFamiliarity,
      rec.scores.regulatorySimplicity,
      rec.scores.speedToClose,
      rec.scores.costScore,
      rec.scores.privacyScore || 'N/A',
      rec.scores.overallScore,
    ])
  })

  const scoringSheet = XLSX.utils.aoa_to_sheet(scoringData)
  XLSX.utils.book_append_sheet(wb, scoringSheet, 'Detailed Scores')

  const considerationsData = [['Jurisdiction', 'Key Considerations']]

  recommendations.forEach((rec) => {
    rec.keyConsiderations?.forEach((consideration: string, index: number) => {
      considerationsData.push([index === 0 ? rec.jurisdiction : '', consideration])
    })
    considerationsData.push(['', ''])
  })

  const considerationsSheet = XLSX.utils.aoa_to_sheet(considerationsData)
  XLSX.utils.book_append_sheet(wb, considerationsSheet, 'Key Considerations')

  const nextStepsData = [
    ['RECOMMENDED NEXT STEPS'],
    [''],
    ['1. LEGAL REVIEW'],
    ['   Engage qualified legal counsel in your selected jurisdiction'],
    ['   Recommended firms available in GNCO platform'],
    [''],
    ['2. STRUCTURE FINALIZATION'],
    ['   Review jurisdiction-specific requirements'],
    ['   Confirm LP domicile mix and tax implications'],
    ['   Determine final fund vehicle and share class structure'],
    [''],
    ['3. FORMATION DOCUMENTS'],
    ['   Limited Partnership Agreement (LPA)'],
    ['   Private Placement Memorandum (PPM)'],
    ['   Subscription Agreements'],
    ['   Side Letters (if applicable)'],
    [''],
    ['4. REGULATORY FILINGS'],
    ['   Form D filing (if US LPs)'],
    ['   State blue sky notices'],
    ['   Jurisdiction-specific registrations'],
    [''],
    ['5. OPERATIONAL SETUP'],
    ['   Bank account opening'],
    ['   Fund administrator engagement'],
    ['   Audit firm selection'],
    ['   Investor reporting systems'],
    [''],
    ['Generated by GNCO — Global Fund Architect'],
    ['https://gnconew.vercel.app'],
    [''],
    ['DISCLAIMER: This analysis is for informational purposes only.'],
    ['Not legal, tax, or investment advice. Consult qualified professionals.'],
  ]
  const nextStepsSheet = XLSX.utils.aoa_to_sheet(nextStepsData)
  XLSX.utils.book_append_sheet(wb, nextStepsSheet, 'Next Steps')

  const fileName = `GNCO_Fund_Analysis_${new Date().toISOString().split('T')[0]}.xlsx`
  XLSX.writeFile(wb, fileName)
}
