import type { JurisdictionProfile } from './types'

export const JURISDICTIONS: JurisdictionProfile[] = [
  {
    id: 'cayman-islands',
    name: 'Cayman Islands',
    region: 'americas',
    flag: '🇰🇾',
    primaryVehicles: ['Exempted Limited Partnership (ELP)', 'Exempted Company', 'Segregated Portfolio Company (SPC)'],
    regulator: 'Cayman Islands Monetary Authority (CIMA)',
    taxTreatyStrength: 'limited',
    setupTimeWeeks: { min: 4, max: 8 },
    annualCostRange: { min: 23000, max: 41400 },
    formationCostRange: { min: 41400, max: 73600 },
    bestFor: ['Global PE and hedge fund structures', 'US tax-exempt LP participation', 'Fast launch for first close timing', 'Master-feeder structures'],
    notIdealFor: ['Treaty-driven withholding optimization', 'Managers needing large domestic treaty networks'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['Maples Fund Services', 'Apex Group', 'MUFG Investor Services'],
      lawFirms: ['Maples and Calder', 'Walkers', 'Ogier'],
      auditors: ['KPMG', 'EY'],
    },
    taxTreaties: ['United Kingdom', 'Ireland', 'Japan', 'UAE', 'Bahrain'],
    fatcaStatus: 'Model 1 IGA with the United States; CRS implemented.',
    notes: 'Still the default for many global alternatives strategies due to legal predictability and operational depth.'
  },
  {
    id: 'luxembourg',
    name: 'Luxembourg',
    region: 'europe',
    flag: '🇱🇺',
    primaryVehicles: ['SCSp', 'RAIF', 'SIF', 'SICAV-SIF'],
    regulator: 'Commission de Surveillance du Secteur Financier (CSSF)',
    taxTreatyStrength: 'high',
    setupTimeWeeks: { min: 8, max: 16 },
    annualCostRange: { min: 46000, max: 92000 },
    formationCostRange: { min: 92000, max: 184000 },
    bestFor: ['Pan-European fundraising', 'Large institutional LP bases', 'Treaty-driven cross-border investing', 'AIFMD-compatible fund platforms'],
    notIdealFor: ['Very small first-time funds with tight budgets', 'Managers requiring ultra-fast launch timelines'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['Alter Domus', 'IQ-EQ', 'Aztec Group'],
      lawFirms: ['Arendt & Medernach', 'Elvinger Hoss Prussen', 'A&O Shearman Luxembourg'],
      auditors: ['PwC', 'Deloitte'],
    },
    taxTreaties: ['France', 'Germany', 'United Kingdom', 'United States', 'China', 'India', 'Netherlands', 'Switzerland'],
    fatcaStatus: 'Model 1 IGA with the United States; CRS implemented.',
    notes: 'RAIF + SCSp remains a common route for sophisticated managers wanting speed with institutional optics.'
  },
  {
    id: 'delaware-usa',
    name: 'Delaware, USA',
    region: 'americas',
    flag: '🇺🇸',
    primaryVehicles: ['Delaware Limited Partnership', 'Delaware LLC', 'Statutory Trust'],
    regulator: 'Delaware Division of Corporations / SEC (federal overlays)',
    taxTreatyStrength: 'limited',
    setupTimeWeeks: { min: 2, max: 6 },
    annualCostRange: { min: 9200, max: 23000 },
    formationCostRange: { min: 18400, max: 46000 },
    bestFor: ['US-centric manager and LP base', 'Tax-exempt and ERISA-aware structures', 'Simple domestic GP/management company stack'],
    notIdealFor: ['Non-US LPs sensitive to ECI/USRPI complexity', 'Treaty-heavy outbound investing mandates'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['SEI', 'SS&C GlobeOp', 'Apex Group'],
      lawFirms: ['Kirkland & Ellis', 'Latham & Watkins', 'Goodwin Procter'],
      auditors: ['KPMG', 'RSM'],
    },
    taxTreaties: ['United Kingdom', 'Canada', 'Germany', 'Japan', 'France'],
    fatcaStatus: 'Domestic FATCA regime; US does not adopt CRS.',
    notes: 'Delaware remains highly efficient for US sponsor-led private funds with domestic reporting expectations.'
  },
  {
    id: 'singapore',
    name: 'Singapore',
    region: 'asia-pacific',
    flag: '🇸🇬',
    primaryVehicles: ['Variable Capital Company (VCC)', 'Limited Partnership', 'Private Company Limited by Shares'],
    regulator: 'Monetary Authority of Singapore (MAS)',
    taxTreatyStrength: 'high',
    setupTimeWeeks: { min: 8, max: 14 },
    annualCostRange: { min: 27600, max: 55200 },
    formationCostRange: { min: 46000, max: 92000 },
    bestFor: ['Asia-focused private capital', 'Family office and wealth hub strategies', 'Managers seeking substance in APAC', 'Treaty-supported outbound investing'],
    notIdealFor: ['Ultra-low-cost launch mandates', 'Purely US domestic fundraises'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['HSBC Securities Services', 'Apex Group', 'Tricor'],
      lawFirms: ['Allen & Gledhill', 'WongPartnership', 'Rajah & Tann'],
      auditors: ['PwC', 'EY'],
    },
    taxTreaties: ['China', 'India', 'Indonesia', 'Vietnam', 'United Kingdom', 'Australia', 'Japan', 'UAE'],
    fatcaStatus: 'Model 1 IGA with the United States; CRS implemented.',
    notes: 'The VCC regime is now mainstream for regional managers consolidating multi-fund umbrellas.'
  },
  {
    id: 'ireland',
    name: 'Ireland',
    region: 'europe',
    flag: '🇮🇪',
    primaryVehicles: ['ILP (Irish Investment Limited Partnership)', 'ICAV', 'QIAIF'],
    regulator: 'Central Bank of Ireland (CBI)',
    taxTreatyStrength: 'high',
    setupTimeWeeks: { min: 10, max: 18 },
    annualCostRange: { min: 46000, max: 92000 },
    formationCostRange: { min: 92000, max: 184000 },
    bestFor: ['EU passported alternatives', 'US manager access to EU allocators', 'Credit and infrastructure mandates'],
    notIdealFor: ['Managers needing very fast close', 'Sub-$50m emerging manager vehicles'],
    coverageStatus: 'partial',
    keyServiceProviders: {
      administrators: ['State Street', 'Northern Trust', 'Citco'],
      lawFirms: ['Matheson', 'A&L Goodbody', 'Arthur Cox'],
      auditors: ['KPMG', 'PwC'],
    },
    taxTreaties: ['United States', 'United Kingdom', 'Germany', 'France', 'Netherlands', 'Japan', 'Singapore'],
    fatcaStatus: 'Model 1 IGA with the United States; CRS implemented.',
    notes: 'ILP reforms improved competitiveness for PE and private credit, especially where EU marketing is core.'
  },
  {
    id: 'bvi',
    name: 'British Virgin Islands (BVI)',
    region: 'americas',
    flag: '🇻🇬',
    primaryVehicles: ['BVI Business Company', 'Limited Partnership', 'Approved Fund / Incubator Fund'],
    regulator: 'BVI Financial Services Commission (FSC)',
    taxTreatyStrength: 'limited',
    setupTimeWeeks: { min: 3, max: 7 },
    annualCostRange: { min: 18400, max: 36800 },
    formationCostRange: { min: 27600, max: 55200 },
    bestFor: ['Cost-sensitive offshore structures', 'Emerging manager launches', 'Rapid SPV and co-invest platforms'],
    notIdealFor: ['Large institutional LP pools requiring deep familiarity', 'Treaty-reliant investing structures'],
    coverageStatus: 'partial',
    keyServiceProviders: {
      administrators: ['Trident Fund Services', 'Apex Group', 'Sanne (Apex)'],
      lawFirms: ['Harneys', 'Conyers', 'Ogier'],
      auditors: ['KPMG', 'BDO'],
    },
    taxTreaties: ['United Kingdom', 'Switzerland', 'Japan', 'UAE', 'China'],
    fatcaStatus: 'Model 1 IGA with the United States; CRS implemented.',
    notes: 'Often used as a pragmatic alternative when timeline and setup cost dominate design decisions.'
  },
  {
    id: 'jersey',
    name: 'Jersey (Channel Islands)',
    region: 'europe',
    flag: '🇯🇪',
    primaryVehicles: ['Jersey Private Fund (JPF)', 'Jersey Limited Partnership', 'Expert Fund'],
    regulator: 'Jersey Financial Services Commission (JFSC)',
    taxTreatyStrength: 'medium',
    setupTimeWeeks: { min: 6, max: 12 },
    annualCostRange: { min: 27600, max: 55200 },
    formationCostRange: { min: 46000, max: 92000 },
    bestFor: ['UK and EU adjacent fundraising', 'Real estate and infrastructure funds', 'Managers wanting common-law familiarity'],
    notIdealFor: ['Deep treaty-optimization structures', 'US retail distribution ambitions'],
    coverageStatus: 'partial',
    keyServiceProviders: {
      administrators: ['JTC', 'IQ-EQ', 'Ocorian'],
      lawFirms: ['Mourant', 'Carey Olsen', 'Ogier'],
      auditors: ['Deloitte', 'PwC'],
    },
    taxTreaties: ['United Kingdom', 'Luxembourg', 'Singapore', 'UAE', 'Guernsey', 'Hong Kong'],
    fatcaStatus: 'Model 1 IGA with the United States; CRS implemented.',
    notes: 'JPF approval speed and pragmatic regulation make Jersey a frequent choice for mid-market managers.'
  },
  {
    id: 'guernsey',
    name: 'Guernsey (Channel Islands)',
    region: 'europe',
    flag: '🇬🇬',
    primaryVehicles: ['Guernsey Limited Partnership', 'Private Investment Fund (PIF)', 'Protected Cell Company'],
    regulator: 'Guernsey Financial Services Commission (GFSC)',
    taxTreatyStrength: 'medium',
    setupTimeWeeks: { min: 6, max: 12 },
    annualCostRange: { min: 27600, max: 55200 },
    formationCostRange: { min: 46000, max: 92000 },
    bestFor: ['Private equity and infrastructure structures', 'Managers targeting UK-linked LPs', 'Governance-focused institutional mandates'],
    notIdealFor: ['Very broad treaty planning', 'Teams needing extensive onshore substance incentives'],
    coverageStatus: 'coming-soon',
    keyServiceProviders: {
      administrators: ['Northern Trust', 'JTC', 'Apex Group'],
      lawFirms: ['Carey Olsen', 'Mourant', 'Collas Crill'],
      auditors: ['EY', 'KPMG'],
    },
    taxTreaties: ['United Kingdom', 'Luxembourg', 'Ireland', 'Singapore', 'Hong Kong'],
    fatcaStatus: 'Model 1 IGA with the United States; CRS implemented.',
    notes: 'Guernsey is often selected for governance quality and depth in closed-ended alternatives servicing.'
  },
  {
    id: 'netherlands',
    name: 'Netherlands',
    region: 'europe',
    flag: '🇳🇱',
    primaryVehicles: ['CV (Commanditaire Vennootschap)', 'FGR', 'Coöperatie'],
    regulator: 'Authority for the Financial Markets (AFM) / Dutch Central Bank (DNB)',
    taxTreatyStrength: 'high',
    setupTimeWeeks: { min: 8, max: 14 },
    annualCostRange: { min: 36800, max: 73600 },
    formationCostRange: { min: 55200, max: 110400 },
    bestFor: ['Treaty-based withholding efficiency', 'Pan-European holding platforms', 'Credit and infrastructure origination'],
    notIdealFor: ['Sponsors prioritizing launch speed over structure quality', 'Low-substance offshore-only models'],
    coverageStatus: 'partial',
    keyServiceProviders: {
      administrators: ['TMF Group', 'Intertrust', 'CSC'],
      lawFirms: ['De Brauw Blackstone Westbroek', 'Loyens & Loeff', 'Stibbe'],
      auditors: ['PwC', 'KPMG'],
    },
    taxTreaties: ['United States', 'United Kingdom', 'Germany', 'France', 'China', 'India', 'Japan', 'Switzerland'],
    fatcaStatus: 'Model 1 IGA with the United States; CRS implemented.',
    notes: 'Still strong for treaty-centric holding designs when substance and transfer-pricing are planned properly.'
  },
  {
    id: 'united-kingdom',
    name: 'United Kingdom',
    region: 'europe',
    flag: '🇬🇧',
    primaryVehicles: ['English Limited Partnership', 'Scottish Limited Partnership', 'Authorised Contractual Scheme (ACS)'],
    regulator: 'Financial Conduct Authority (FCA)',
    taxTreatyStrength: 'high',
    setupTimeWeeks: { min: 6, max: 12 },
    annualCostRange: { min: 27600, max: 55200 },
    formationCostRange: { min: 36800, max: 73600 },
    bestFor: ['UK institutional allocator familiarity', 'Credit and real assets managers', 'Common-law governance preference'],
    notIdealFor: ['Sponsors seeking low-disclosure offshore optics', 'Certain non-UK tax-neutral pooling objectives'],
    coverageStatus: 'partial',
    keyServiceProviders: {
      administrators: ['Langham Hall', 'Apex Group', 'Aztec Group'],
      lawFirms: ['Travers Smith', 'Macfarlanes', 'Debevoise & Plimpton'],
      auditors: ['Deloitte', 'EY'],
    },
    taxTreaties: ['United States', 'Luxembourg', 'Netherlands', 'Germany', 'France', 'Singapore', 'UAE', 'India'],
    fatcaStatus: 'Model 1 IGA with the United States; CRS implemented.',
    notes: 'UK LP structures remain heavily used despite tighter transparency and beneficial ownership frameworks.'
  },
  {
    id: 'hong-kong',
    name: 'Hong Kong',
    region: 'asia-pacific',
    flag: '🇭🇰',
    primaryVehicles: ['Limited Partnership Fund (LPF)', 'Open-ended Fund Company (OFC)'],
    regulator: 'Securities and Futures Commission (SFC)',
    taxTreatyStrength: 'medium',
    setupTimeWeeks: { min: 6, max: 10 },
    annualCostRange: { min: 36800, max: 73600 },
    formationCostRange: { min: 46000, max: 92000 },
    bestFor: ['Greater China deal pipelines', 'Asia credit and growth equity', 'Managers with Hong Kong operating teams'],
    notIdealFor: ['US tax-exempt heavy investor pools without blocker planning', 'EU marketing-first strategies'],
    coverageStatus: 'coming-soon',
    keyServiceProviders: {
      administrators: ['Vistra', 'Tricor', 'HSBC Securities Services'],
      lawFirms: ['Deacons', 'Mayer Brown', 'Sidley Austin'],
      auditors: ['PwC', 'KPMG'],
    },
    taxTreaties: ['China', 'Singapore', 'Japan', 'United Kingdom', 'Netherlands', 'India'],
    fatcaStatus: 'Model 2 IGA with the United States; CRS implemented.',
    notes: 'The LPF regime has gained traction for Asia-focused funds seeking a domestic onshore alternative.'
  },
  {
    id: 'mauritius',
    name: 'Mauritius',
    region: 'middle-east',
    flag: '🇲🇺',
    primaryVehicles: ['Global Business Company (GBC)', 'Limited Partnership', 'Protected Cell Company'],
    regulator: 'Financial Services Commission Mauritius (FSC Mauritius)',
    taxTreatyStrength: 'medium',
    setupTimeWeeks: { min: 6, max: 10 },
    annualCostRange: { min: 18400, max: 36800 },
    formationCostRange: { min: 27600, max: 55200 },
    bestFor: ['Africa- and India-linked investment corridors', 'Middle Eastern capital pools', 'Cost-aware cross-border structures'],
    notIdealFor: ['Broad EU institutional fundraising without additional structuring', 'Managers requiring top-tier global administrator depth'],
    coverageStatus: 'coming-soon',
    keyServiceProviders: {
      administrators: ['IQ-EQ Mauritius', 'Apex Group Mauritius', 'Intercontinental Trust'],
      lawFirms: ['BLC Robert & Associates', 'ENSafrica Mauritius', 'Appleby Mauritius'],
      auditors: ['EY', 'BDO'],
    },
    taxTreaties: ['India', 'South Africa', 'UAE', 'France', 'China', 'Kenya', 'Rwanda'],
    fatcaStatus: 'Model 1 IGA with the United States; CRS implemented.',
    notes: 'Mauritius remains relevant for treaty-supported African deployment and GCC investor structuring.'
  },
  {
    id: 'malta',
    name: 'Malta',
    region: 'europe',
    flag: '🇲🇹',
    primaryVehicles: ['Notified AIF', 'SICAV', 'Limited Partnership en Commandite'],
    regulator: 'Malta Financial Services Authority (MFSA)',
    taxTreatyStrength: 'medium',
    setupTimeWeeks: { min: 8, max: 14 },
    annualCostRange: { min: 36800, max: 73600 },
    formationCostRange: { min: 55200, max: 110400 },
    bestFor: ['EU-focused boutique managers', 'Alternative UCITS-adjacent strategies', 'Cost-conscious European structures'],
    notIdealFor: ['Mega-fund institutional first closes', 'Managers needing top-speed launch execution'],
    coverageStatus: 'coming-soon',
    keyServiceProviders: {
      administrators: ['Apex Group Malta', 'Alter Domus Malta', 'BOV Fund Services'],
      lawFirms: ['Camilleri Preziosi', 'Ganado Advocates', 'WH Partners'],
      auditors: ['PwC', 'KPMG'],
    },
    taxTreaties: ['United Kingdom', 'France', 'Germany', 'Italy', 'Netherlands', 'UAE'],
    fatcaStatus: 'Model 1 IGA with the United States; CRS implemented.',
    notes: 'Malta can be attractive for smaller EU managers balancing regulatory access with moderate operating cost.'
  },
  {
    id: 'switzerland',
    name: 'Switzerland',
    region: 'europe',
    flag: '🇨🇭',
    primaryVehicles: ['Swiss Limited Partnership for Collective Investment (KmGK)', 'SICAV', 'Contractual Fund'],
    regulator: 'Swiss Financial Market Supervisory Authority (FINMA)',
    taxTreatyStrength: 'high',
    setupTimeWeeks: { min: 10, max: 18 },
    annualCostRange: { min: 55200, max: 110400 },
    formationCostRange: { min: 92000, max: 184000 },
    bestFor: ['High-governance institutional mandates', 'Swiss and DACH investor ecosystems', 'Long-duration real assets and private markets'],
    notIdealFor: ['First-time sub-$100m funds', 'Teams prioritizing low-cost administration'],
    coverageStatus: 'coming-soon',
    keyServiceProviders: {
      administrators: ['CACEIS Switzerland', 'Swissquote Fund Services', 'Société Générale Securities Services Switzerland'],
      lawFirms: ['Lenz & Staehelin', 'Bär & Karrer', 'Niederer Kraft Frey'],
      auditors: ['EY', 'KPMG'],
    },
    taxTreaties: ['United States', 'Germany', 'France', 'United Kingdom', 'Netherlands', 'Singapore', 'Japan'],
    fatcaStatus: 'Model 2 IGA with the United States; CRS implemented.',
    notes: 'Swiss structures emphasize investor protection and governance but typically come with higher cost and lead time.'
  },
  {
    id: 'cyprus',
    name: 'Cyprus',
    region: 'europe',
    flag: '🇨🇾',
    primaryVehicles: ['AIF with Limited Number of Persons (AIFLNP)', 'RAIF (Cyprus)', 'Limited Partnership'],
    regulator: 'Cyprus Securities and Exchange Commission (CySEC)',
    taxTreatyStrength: 'medium',
    setupTimeWeeks: { min: 8, max: 14 },
    annualCostRange: { min: 25000, max: 45000 },
    formationCostRange: { min: 40000, max: 75000 },
    bestFor: ['Eastern Mediterranean and CEE investment flows', 'Cost-efficient EU-compliant structures', 'Mid-market PE and VC launches'],
    notIdealFor: ['Top-tier institutional re-up pools needing long track record jurisdictions', 'Ultra-fast launch requirements'],
    coverageStatus: 'coming-soon',
    keyServiceProviders: {
      administrators: ['Trident Trust Cyprus', 'Apex Group Cyprus', 'Kreston Proios'],
      lawFirms: ['Chrysses Demetriades & Co', 'Elias Neocleous & Co', 'Harris Kyriakides'],
      auditors: ['Deloitte', 'PwC'],
    },
    taxTreaties: ['United Kingdom', 'Germany', 'France', 'India', 'China', 'UAE', 'Netherlands'],
    fatcaStatus: 'Model 1 IGA with the United States; CRS implemented.',
    notes: 'Cyprus is often considered for managers seeking EU structure access with comparatively lower operating spend.'
  },
]
